# Configure le port par défaut de l'application (8080 par défaut)
quarkus.http.port=8080
quarkus.http.root-path=/

# Indique à Quarkus d'utiliser le registre GitHub
quarkus.container-image.registry=ghcr.io

# Quarkus utilisera automatiquement la variable 'version' définie dans votre build.gradle


# Votre nom d'utilisateur GitHub (IMPORTANT : en minuscules !)
quarkus.container-image.group=ericheartsong
quarkus.container-image.name=fougere-api

# Paramètres requis pour Render
quarkus.http.host=0.0.0.0

#connexion à mongodb
# Chaîne de connexion standard pour MongoDB Atlas
quarkus.mongodb.connection-string = mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@cluster0.cofzuxr.mongodb.net/?retryWrites=true&w=majority

# Nom de votre base de données sur Atlas
quarkus.mongodb.database = fougere

# Force la console à afficher les logs à partir du niveau INFO (et les erreurs)
quarkus.log.console.level=INFO

# Supprime la limite d'affichage des stacktraces pour voir l'erreur en entier
quarkus.log.console.stack-trace-element-max-results=all
